name: Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Install Uploader
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -O uploader
          chmod 777 ./uploader
          echo ${{ secrets.GITHUB_TOKEN }} > auth.json
      - name: Download Dll
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          name: Puerts_Unity_Plugins
          path: ./unity/Assets/Plugins/
          repo: Tencent/puerts
      - name: Zip
        run: |
          zip -q -r "puerts-unity-${{ github.sha }}.zip" ./unity/Assets
          zip -q -r "puerts-unreal-${{ github.sha }}.zip" ./unreal
      - name: Upload
        run: |
          ls
          ./uploader -s ./puerts-unity-${{ github.sha }}.zip -r tencent/puerts/unity
          ./uploader -s ./puerts-unreal-${{ github.sha }}.zip -r tencent/puerts/unreal
          
