name: Publish

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: Tencent/puerts
      - name: Install Uploader
        run: |
          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -O uploader
          chmod 777 ./uploader
          echo ${{ secrets.GITHUB_TOKEN }} > auth.json
